// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Test.Context
{
    public partial class ProductPrice
    {
        [Key]
        public int Id { get; set; }
        public int? ProductId { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Price { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("ProductId")]
        [InverseProperty("ProductPrice")]
        public virtual Product Product { get; set; }
    }
}