// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Test.Context
{
    public partial class Product
    {
        public Product()
        {
            OrderItems = new HashSet<OrderItems>();
            ProductPrice = new HashSet<ProductPrice>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(60)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Description { get; set; }
        [Required]
        public bool? IsTaxable { get; set; }
        public bool Active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        [StringLength(60)]
        [Unicode(false)]
        public string CreateBy { get; set; }

        [InverseProperty("Product")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<ProductPrice> ProductPrice { get; set; }
    }
}